name: Bump version (prerelease)

on:
  push:
    branches:
      - dev

jobs:
  bump-and-release:
    name: Create prerelease
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Create bump
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          changelog_increment_filename: CURRENT.md
          extra_requirements: 'cz-nhm'
          prerelease: alpha
          changelog: false
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: 'CURRENT.md'
          tag_name: v${{ env.REVISION }}
          prerelease: true
          target_commitish: dev
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
